#coding=utf-8
"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.utils.translation import ugettext_lazy as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEPLOY_DIR = os.path.join(BASE_DIR, 'scripts', 'deploy')

PYTHON_PATH = '/home/comingchina/.pythonbrew/venvs/Python-2.7.6/web/bin/python'

#邮件存储目录
DATA_PATH = os.path.join(BASE_DIR, '..', 'data')
DATA_RCPTS_PATH = os.path.join(DATA_PATH, 'rcpts-get')
DATA_MAILS_PATH = os.path.join(DATA_PATH, 'mails-get')
DATA_ERROR_PATH = os.path.join(DATA_PATH, 'mails-error')
SYNC_SERVER = 'shenzhen'
SERVER_ID = 'hangzhou'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w5+sh+rt!bg2_&)x)^11tn&^86jtq7+4im*0&-&3-k_(r^d)h('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['http://202.103.191.28']

AUTH_USER_MODEL = 'core.Customer'
LOGIN_URL = '/login'
LANGUAGES = (
    ('en', _(u'English')),
    ('zh-cn', _(u'中文简体')),
    # ('zh-tw', _(u'中文繁體')),
)



# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.mail',
    'apps.collect_mail',
    'apps.core',
    'bootstrapform',
    'captcha',

)
# AUTH_USER_MODEL = 'core.MyUser'
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissions'
    ]
}

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
)

ROOT_URLCONF = 'web_customer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_customer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django_postgrespool',
        'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'mail-relay',                      # Or path to database file if using sqlite3.
        # 'USER': 'postgres',                      # Not used with sqlite3.
        'USER': 'umail',                      # Not used with sqlite3.
        # 'PASSWORD': '1234',                  # Not used with sqlite3.
        'PASSWORD': 'NDg1YjFjY2ZjMzgxN2Rm',
        # 'HOST': 'localhost',                      # Set to empty string for localhost. Not used with sqlite3.
        'HOST': '115.238.86.83',                      # Set to empty string for localhost. Not used with sqlite3.
        # 'PORT': '5432',                      # Set to empty string for default. Not used with sqlite3.
        'PORT': '45600',                      # Set to empty string for default. Not used with sqlite3.
    }
}

# CACHES = {
#     'default': {
#         'BACKEND': 'django_cache.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/0',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'redis_cache.client.DefaultClient',
             # "CONNECTION_POOL_KWARGS": {"max_connections": 100}
            # 'PASSWORD': 'secretpassword',  # Optional
        # }
    # }
# }

CACHES = {
    'default': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': '127.0.0.1:6379:0',
        'OPTIONS': {
            'CLIENT_CLASS': 'redis_cache.client.DefaultClient',
            # 'PASSWORD': 'secretpassword',  # Optional
        }
    }
}


PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.UnsaltedMD5PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
)


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
