# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 09:45
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='customer_id', default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=50)),
                ('linkman', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7535\u8bdd')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u624b\u673a')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u90ae\u7bb1')),
                ('im', models.CharField(blank=True, max_length=50, null=True, verbose_name='QQ/MSN')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u5730\u5740')),
            ],
            options={
                'db_table': 'core_customer',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommonVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_type', models.CharField(choices=[(b'joke', '\u7b11\u8bdd\u5e93'), (b'motto', '\u683c\u8a00\u5e93'), (b'health', '\u517b\u751f\u5e93')], max_length=10, verbose_name='\u516c\u5171\u53d8\u91cf\u7c7b\u578b')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'core_common_var',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u533a\u57df\u540d\u79f0')),
            ],
            options={
                'db_table': 'core_customer_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('user_type', models.CharField(choices=[(b'', '--'), (b'users', '\u666e\u901a\u7528\u6237'), (b'manager', '\u7ba1\u7406\u5458'), (b'system', '\u7cfb\u7edf'), (b'super', '\u8d85\u7ea7\u7528\u6237'), (b'agents', '\u4ee3\u7406\u7528\u6237')], default='manager', max_length=20, verbose_name='\u7528\u6237\u7c7b\u578b')),
                ('target_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u540d\u79f0')),
                ('action', models.CharField(choices=[(b'add_account', '\u6dfb\u52a0\u7fa4\u53d1\u5e10\u6237'), (b'edit_account', '\u4fee\u6539\u5e10\u6237\u4fe1\u606f'), (b'del_account', '\u5220\u9664\u7fa4\u53d1\u5e10\u6237'), (b'init_service', '\u521d\u59cb\u5316\u7fa4\u53d1\u670d\u52a1'), (b'set_service', '\u66f4\u6539\u7fa4\u53d1\u670d\u52a1\u8bbe\u7f6e'), (b'add_ip', '\u6dfb\u52a0IP\u5730\u5740'), (b'del_ip', '\u5220\u9664IP\u5730\u5740'), (b'add_domain', '\u6dfb\u52a0\u57df\u540d'), (b'del_domain', '\u5220\u9664\u57df\u540d'), (b'add_mailbox', '\u6dfb\u52a0\u53d1\u9001\u5e10\u53f7'), (b'set_mailbox', '\u4fee\u6539\u53d1\u9001\u5e10\u53f7'), (b'del_mailbox', '\u5220\u9664\u53d1\u9001\u5e10\u53f7'), (b'update_count', '\u4fee\u6539\u7fa4\u53d1\u91cf'), (b'sys_auto_return', '\u7cfb\u7edf\u81ea\u52a8\u8fd4\u91cf'), (b'disable_account', '\u5220\u9664\u7fa4\u53d1\u5e10\u6237'), (b'recover_account', '\u6062\u590d\u7fa4\u53d1\u5e10\u6237')], db_index=True, default='', max_length=20, verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('desc', models.TextField(verbose_name='\u8bf4\u660e')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u540d\u79f0')),
            ],
            options={
                'db_table': 'core_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreLoginAreaIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5f00\u542f\u767b\u9646\u4fdd\u62a4')),
                ('area', models.TextField(help_text='\u533a\u57df\u4e4b\u95f4\u7528\u201c,\u201d\u53f7\u9694\u5f00', verbose_name='\u5ba2\u6237\u767b\u9646\u6240\u5c5e\u533a\u57df')),
                ('ip', models.TextField(help_text='IP\u4e4b\u95f4\u7528\u201c,\u201d\u53f7\u9694\u5f00', verbose_name='\u5ba2\u6237\u767b\u9646\u6240\u5c5eIP')),
            ],
            options={
                'db_table': 'core_customer_area_ip_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorePasswordAlter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, verbose_name='UUID')),
                ('token', models.CharField(max_length=50, verbose_name='TOKEN')),
                ('isvalid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5b9e\u73b0')),
                ('expire_time', models.FloatField(default=0, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
            ],
            options={
                'db_table': 'core_password_alter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreSuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=1, verbose_name='\u8bc4\u4ef7\u7ea7\u522b')),
                ('suggest', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5efa\u8bae')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'core_suggest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='\u4e0d\u5efa\u8bae\u6dfb\u52a0\u4f01\u4e1a\u90ae\u7bb1\u57df\u540d\uff0c\u5c06\u5bfc\u81f4\u4f01\u4e1a\u90ae\u7bb1\u6536\u4fe1\u5f02\u5e38\uff0c\u5efa\u8bae\u5728\u5df2\u6709\u4f01\u4e1a\u90ae\u7bb1\u57df\u540d\u7684\u60c5\u51b5\u4e0b\u521b\u5efa\u4e8c\u7ea7\u57df\u540d\u3002', max_length=100, verbose_name='\u53d1\u9001\u57df\u540d')),
                ('status', models.CharField(choices=[(b'Y', '\u9a8c\u8bc1\u901a\u8fc7'), (b'N', '\u5f85\u9a8c\u8bc1'), (b'f', '\u9a8c\u8bc1\u672a\u901a\u8fc7')], default='N', max_length=1, verbose_name='\u72b6\u6001')),
                ('dkim_selector', models.CharField(blank=True, default='umail', max_length=50, null=True, verbose_name='\u5b50\u57df\u540d')),
                ('dkim_private', models.TextField(blank=True, null=True, verbose_name='\u79c1\u94a5')),
                ('dkim_public', models.TextField(blank=True, null=True, verbose_name='\u516c\u94a5')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_spf', models.CharField(choices=[(b'Y', '\u9a8c\u8bc1\u901a\u8fc7'), (b'N', '\u5f85\u9a8c\u8bc1'), (b'f', '\u9a8c\u8bc1\u672a\u901a\u8fc7')], default='N', max_length=1, verbose_name='spf\u68c0\u6d4b\u72b6\u6001')),
                ('is_mx', models.CharField(choices=[(b'Y', '\u9a8c\u8bc1\u901a\u8fc7'), (b'N', '\u5f85\u9a8c\u8bc1'), (b'f', '\u9a8c\u8bc1\u672a\u901a\u8fc7')], default='N', max_length=1, verbose_name='mx\u68c0\u6d4b\u72b6\u6001')),
                ('is_dkim', models.CharField(choices=[(b'Y', '\u9a8c\u8bc1\u901a\u8fc7'), (b'N', '\u5f85\u9a8c\u8bc1'), (b'f', '\u9a8c\u8bc1\u672a\u901a\u8fc7')], default='N', max_length=1, verbose_name='dkim\u68c0\u6d4b\u72b6\u6001')),
            ],
            options={
                'db_table': 'core_customer_domain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerMailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='\u53d1\u9001\u57df\u540d')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u540d\u79f0')),
                ('mailbox', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u90ae\u7bb1\u8d26\u53f7')),
                ('password', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u5bc6\u7801')),
                ('disabled', models.CharField(blank=True, choices=[(b'0', '\u6b63\u5e38'), (b'1', '\u7981\u7528')], default='0', max_length=1, null=True, verbose_name='\u662f\u5426\u7981\u7528')),
            ],
            options={
                'db_table': 'core_mailbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(editable=False, max_length=50, unique=True, verbose_name='\u8ba2\u5355\u53f7')),
                ('product_desc', models.CharField(max_length=128, verbose_name='\u5546\u54c1\u63cf\u8ff0')),
                ('product_detail', models.TextField(max_length=1000, verbose_name='\u5546\u54c1\u8be6\u60c5')),
                ('fee', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='\u91d1\u989d(\u5355\u4f4d:\u5143)')),
                ('qty_buy', models.IntegerField(default=0, verbose_name='\u8d2d\u4e70\u70b9\u6570')),
                ('attach', models.CharField(blank=True, max_length=127, null=True, verbose_name='\u9644\u52a0\u6570\u636e')),
                ('dt_start', models.DateTimeField(blank=True, null=True, verbose_name='\u4ea4\u6613\u5f00\u59cb\u65f6\u95f4')),
                ('dt_end', models.DateTimeField(blank=True, null=True, verbose_name='\u4ea4\u6613\u5931\u6548\u65f6\u95f4')),
                ('dt_pay', models.DateTimeField(blank=True, null=True, verbose_name='\u4ed8\u6b3e\u65f6\u95f4')),
                ('status', models.CharField(choices=[(b'waiting', '\u7b49\u5f85\u4ed8\u6b3e'), (b'paied', '\u5df2\u4ed8\u6b3e'), (b'lapsed', '\u5df2\u5931\u6548'), (b'cancel', '\u5df2\u53d6\u6d88')], default='waiting', max_length=10, verbose_name='\u72b6\u6001')),
                ('payway', models.CharField(choices=[(b'WEIXIN', '\u5fae\u4fe1\u652f\u4ed8'), (b'ALI', '\u652f\u4ed8\u5b9d\u652f\u4ed8')], default=b'WEIXIN', max_length=10, verbose_name='\u652f\u4ed8\u65b9\u5f0f')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'core_customer_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerTplSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(choices=[(b'base64', 'base64'), (b'quoted-printable', 'quoted-printable')], default='base64', max_length=50, verbose_name='\u90ae\u4ef6\u7f16\u7801')),
                ('character', models.CharField(choices=[(b'utf-8', 'utf-8'), (b'iso-8859-1', 'iso-8859-1'), (b'gb180308', 'gb180308'), (b'euc-jp', 'euc-jp')], default='utf-8', max_length=32, verbose_name='\u8f6c\u6362\u5b57\u7b26\u96c6')),
                ('image_encode', models.CharField(choices=[(b'N', '\u5426'), (b'Y', '\u662f')], default='N', help_text='\u5426\uff1a\u90ae\u4ef6\u5185\u7684\u56fe\u7247\u4f1a\u81ea\u52a8\u4e0a\u4f20\u5230U-Mail\u670d\u52a1\u5668\u4e0a\uff0c\u4ee5\u5916\u90e8\u56fe\u50cf\u94fe\u63a5\u7684\u65b9\u5f0f\u663e\u793a\u56fe\u7247\u3002\u662f\uff1a\u90ae\u4ef6\u6240\u4f7f\u7528\u7684\u56fe\u50cf\u5185\u5d4c\u5728\u90ae\u4ef6\u6d88\u606f\u4e2d\u3002 \u8fd9\u5c06\u5bfc\u81f4\u90ae\u4ef6\u5927\u5c0f\u7684\u589e\u52a0(\u6263\u9664\u66f4\u591a\u7fa4\u53d1\u70b9\u6570), \u4f46\u662f\u90ae\u4ef6\u5374\u53ef\u4ee5\u8131\u673a\u6d4f\u89c8\u3002 ', max_length=32, verbose_name='\u662f\u5426\u5185\u5d4c\u7167\u7247')),
                ('attachtype', models.CharField(choices=[(b'common', '\u4f20\u7edf\u5185\u5d4c\u9644\u4ef6'), (b'html', '\u5728\u7ebf\u9644\u4ef6')], default='common', help_text='\u4f20\u7edf\u9644\u4ef6\uff1a\u4ee5\u666e\u901a\u7684\u90ae\u4ef6\u9644\u4ef6\u5f62\u5f0f\u53d1\u9001\uff0c\u9644\u4ef6\u5927\u5c0f\u4f1a\u589e\u52a0\u90ae\u4ef6\u5927\u5c0f\uff0c\u4f46\u662f\u9644\u4ef6\u53ef\u4ee5\u8131\u673a\u67e5\u770b\u3002\u5728\u7ebf\u9644\u4ef6\uff1a\u90ae\u4ef6\u7684\u9644\u4ef6\u4ee5HTML\u8d85\u94fe\u63a5\u7684\u5f62\u5f0f\u5185\u5d4c\u5728\u90ae\u4ef6\u6d88\u606f\u4e2d\uff0c\u4e0d\u4f1a\u589e\u5927\u90ae\u4ef6\u5927\u5c0f\uff0c\u4f46\u662f\u9700\u8981\u7f51\u7edc\u624d\u53ef\u8bbf\u95ee\u3002 ', max_length=32, verbose_name='\u9644\u4ef6\u8bbe\u7f6e')),
            ],
            options={
                'db_table': 'core_customer_tpl_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultMailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u540d\u79f0')),
            ],
            options={
                'db_table': 'core_mss_default_acct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='\u53d1\u9001\u57df\u540d')),
                ('grant_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4ee3\u7406\u5546')),
            ],
            options={
                'db_table': 'core_domain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='\u5ba2\u6237\u57df\u540d')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u53d1\u4ef6\u4eba\u540d\u79f0')),
                ('mailbox', models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='\u53d1\u4ef6\u4eba\u90ae\u7bb1')),
                ('password', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u5bc6\u7801')),
                ('disabled', models.CharField(choices=[(b'0', '\u6b63\u5e38'), (b'1', '\u7981\u7528')], default='0', max_length=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'core_mailbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, verbose_name='\u7535\u8bdd')),
                ('mobile', models.CharField(max_length=20, verbose_name='\u624b\u673a')),
                ('email', models.CharField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('im', models.CharField(max_length=50, verbose_name='QQ/MSN')),
            ],
            options={
                'db_table': 'core_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='\u952e')),
                ('value', models.TextField(blank=True, null=True, verbose_name='\u503c')),
            ],
            options={
                'db_table': 'core_prefs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trial', models.CharField(choices=[(b'0', b'0'), (b'1', b'1')], default='0', max_length=1, verbose_name='\u662f\u5426\u4e3a\u6d4b\u8bd5\u7528\u6237')),
                ('is_verify', models.CharField(choices=[(b'0', b'0'), (b'1', b'1')], default='0', max_length=1, verbose_name='\u662f\u5426\u4e3a\u5ba1\u6838\u7528\u6237')),
                ('server_type', models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5')], default='0', max_length=1)),
                ('send_type', models.CharField(choices=[(b'local', b'local'), (b'remote', b'remote')], default='local', max_length=16)),
                ('service_type', models.CharField(choices=[(b'all', b'all'), (b'day', b'day')], default='local', max_length=16)),
                ('service_start', models.DateTimeField(default='0000-00-00 00:00:00', verbose_name='\u670d\u52a1\u5f00\u59cb\u65f6\u95f4')),
                ('service_end', models.DateTimeField(default='0000-00-00 00:00:00', verbose_name='\u670d\u52a1\u7ed3\u675f\u65f6\u95f4')),
                ('qty_count', models.IntegerField(default=0)),
                ('qty_valid', models.IntegerField(default=0)),
                ('qty_buytotal', models.IntegerField(default=0)),
                ('error_stat_ratio', models.FloatField(default=0.15)),
                ('refuse_error_stat_ratio', models.FloatField(default=0.5)),
                ('ws_rate_limit', models.IntegerField(default=0)),
                ('module_permit', models.TextField(blank=True, null=True)),
                ('disabled', models.CharField(choices=[(b'0', '\u6b63\u5e38'), (b'1', '\u7981\u7528')], default='0', max_length=1)),
                ('disabled_date', models.DateField(default='0000-00-00')),
                ('track_domain', models.CharField(blank=True, help_text='\u5ba2\u6237\u6307\u5b9a\u57df\u540d\uff0c\u66ff\u6362\u8ddf\u8e2a\u7edf\u8ba1\u94fe\u63a5\u57df\u540d', max_length=100, null=True, verbose_name='\u5ba2\u6237\u6307\u5b9a\u57df\u540d')),
                ('addr_export', models.CharField(choices=[(b'0', b'0'), (b'1', b'1')], default='1', help_text='\u5730\u5740\u6c60\u5bfc\u51fa\u529f\u80fd\uff0c1\u4e3a\u5f00\u542f\uff0c0\u4e3a\u7981\u7528\uff0c\u9ed8\u8ba4\u4e3a1', max_length=1, verbose_name='\u5f00\u542f\u5bfc\u51fa\u6309\u94ae')),
                ('addr_export_max', models.IntegerField(default=0, help_text='\u5730\u5740\u5bfc\u51fa\u6700\u5927\u6570\uff0c0\u4e3a\u65e0\u9650\u5236', verbose_name='\u5730\u5740\u6c60\u5bfc\u51fa\u9650\u5236')),
                ('timezone', models.SmallIntegerField(default=8, help_text='\u65f6\u533a\uff0c\u76f8\u5bf9GMT\u65f6\u95f4\uff0c\u59828\u8868\u793aGMT+8\uff0c\u5317\u4eac\u65f6\u95f4', verbose_name='\u65f6\u533a')),
                ('cannotview_html', models.TextField(blank=True, help_text='\u90ae\u4ef6\u65e0\u6cd5\u6b63\u5e38\u663e\u793a\uff0c\u63d0\u793a\u67e5\u770b\u5728\u7ebf\u7248\u672c\u7684\u5185\u5bb9', null=True)),
                ('unsubscribe_html', models.TextField(blank=True, help_text='\u9000\u8ba2\u90ae\u4ef6\u5217\u8868\u94fe\u63a5\u5185\u5bb9', null=True)),
                ('is_maintain', models.SmallIntegerField(default=0)),
                ('is_high_quality', models.SmallIntegerField(default=0)),
                ('maintain_rate', models.IntegerField(default=50)),
                ('updated', models.DateTimeField(default='0000-00-00 00:00:00', verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'core_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeixinCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionid', models.CharField(max_length=50, unique=True, verbose_name='nionid')),
                ('openid', models.CharField(blank=True, max_length=50, null=True, verbose_name='openid')),
                ('access_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='access_token')),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='refresh_token')),
                ('province', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7701\u4efd')),
                ('headimgurl', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5934\u50cf\u56fe\u7247')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bed\u8a00')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u57ce\u5e02')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u56fd\u5bb6')),
                ('sex', models.CharField(blank=True, choices=[(b'1', '\u7537'), (b'2', '\u5973')], default='1', max_length=20, null=True, verbose_name='\u7701\u4efd')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u540d\u79f0')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'core_weixin_customer',
                'managed': False,
            },
        ),
    ]
