# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u901a\u77e5\u8054\u7cfb\u4eba')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u624b\u673a')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u90ae\u7bb1')),
                ('is_odd_consume', models.BooleanField(default=False, verbose_name='\u5f02\u5e38\u6d88\u8d39\u63d0\u9192')),
                ('is_remote_login', models.BooleanField(default=False, verbose_name='\u5f02\u5730\u767b\u5f55\u63d0\u9192')),
                ('is_odd_domain', models.BooleanField(default=False, verbose_name='\u57df\u540d\u89e3\u6790\u8bb0\u5f55\u5f02\u5e38\u63d0\u9192')),
                ('is_reduce_credit', models.BooleanField(default=False, verbose_name='\u4fe1\u8a89\u5ea6\u964d\u4f4e\u63d0\u9192')),
                ('is_alter_contacts', models.BooleanField(default=False, verbose_name='\u8054\u7cfb\u4eba\u4fe1\u606f\u4fee\u6539\u63d0\u9192')),
                ('is_success_recharge', models.BooleanField(default=False, verbose_name='\u5145\u503c\u6210\u529f\u63d0\u9192')),
            ],
            options={
                'db_table': 'core_notice_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('token', models.CharField(max_length=50, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'core_token_setting',
                'managed': False,
            },
        ),
    ]
