# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-08 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u89e6\u53d1\u5668\u540d\u79f0')),
                ('type', models.CharField(choices=[('open_or_click', '\u4efb\u52a1\u89e6\u53d1\u5668(\u6253\u5f00\u6216\u70b9\u51fb)'), ('birthday', '\u751f\u65e5\u89e6\u53d1\u5668'), ('holiday', '\u8282\u5047\u65e5\u89e6\u53d1\u5668'), ('subscribe', '\u8ba2\u9605\u6216\u9000\u8ba2\u89e6\u53d1\u5668')], max_length=20, verbose_name='\u7c7b\u578b')),
                ('status', models.CharField(choices=[('enable', '\u542f\u7528'), ('disable', '\u7981\u7528'), ('expired', '\u5df2\u8fc7\u671f')], max_length=10, verbose_name='\u72b6\u6001')),
                ('is_permanent', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6c38\u4e45')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u52a8\u4f5c\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6761\u4ef6\u540d\u79f0')),
                ('type', models.CharField(blank=True, choices=[('open', '\u6253\u5f00'), ('click', '\u70b9\u51fb'), ('subscribe', '\u8ba2\u9605'), ('unsubscribe', '\u9000\u8ba2')], max_length=20, null=True, verbose_name='\u6761\u4ef6\u7c7b\u578b')),
                ('con_href', models.CharField(blank=True, max_length=200, null=True)),
                ('con_holiday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerListShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.MailList')),
                ('trigger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trigger.Trigger')),
            ],
        ),
    ]
