CREATE TABLE `core_group` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `domain_id` int(11) NOT NULL DEFAULT '0' COMMENT '所属域名ID',
  `name` varchar(100) CHARACTER SET utf8 NOT NULL COMMENT '组名称',
  `description` text CHARACTER SET utf8 COMMENT '组描述',
  `mail_space` int(11) NOT NULL DEFAULT '0' COMMENT '邮箱空间',
  `net_space` int(11) NOT NULL DEFAULT '0' COMMENT '网络硬盘空间',
  `allow_out_size` int(11) NOT NULL DEFAULT '0' COMMENT '允许外发附件大小',
  `send_limit` tinyint(1) NOT NULL DEFAULT '1' COMMENT '发信功能限制',
  `recv_limit` tinyint(1) NOT NULL DEFAULT '1' COMMENT '收信功能限制',
  `is_limit_send` tinyint(1) NOT NULL DEFAULT '1' COMMENT '限制发送频率',
  `is_pop` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'POP/POPS邮箱收取功能',
  `is_smtp` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'SMTP/SMTPS客户端邮件发送功能',
  `is_imap` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'IMAP/IMAPS客户端邮件收发功能',
  `is_passwd` tinyint(1) NOT NULL DEFAULT '1' COMMENT '定期密码修改设置',
  `passwd_day` int(11) NOT NULL DEFAULT '0' COMMENT '密码有效期',
  `passwd_start` datetime DEFAULT NULL COMMENT '密码有效开始时间',
  `is_passwd_first` tinyint(1) NOT NULL DEFAULT '1' COMMENT '首次登录修改密码',
  `passwd_type` tinyint(1) NOT NULL DEFAULT '2' COMMENT '密码组成字符种类',
  `passwd_other` longtext CHARACTER SET utf8 COMMENT '其他密码规则设置',
  `is_virus` tinyint(1) NOT NULL DEFAULT '1' COMMENT '反病毒功能',
  `is_spam` tinyint(1) NOT NULL DEFAULT '1' COMMENT '反垃圾功能',
  `is_spf` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'SPF检测',
  `is_grey` tinyint(1) NOT NULL DEFAULT '0' COMMENT '灰名单检测',
  `check_attach` longtext CHARACTER SET utf8 COMMENT '检查附件',
  `match_black` longtext CHARACTER SET utf8 COMMENT '匹配黑名单',
  `check_spam` longtext CHARACTER SET utf8 COMMENT '反垃圾引擎',
  `is_formt` tinyint(1) NOT NULL DEFAULT '1' COMMENT '检查发件人格式',
  `spam_folder` varchar(10) CHARACTER SET utf8 NOT NULL DEFAULT 'spam' COMMENT '垃圾邮件投递位置',
  `spam_subject_flag` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '垃圾邮件主题标识',
  `isolate_day` int(11) NOT NULL DEFAULT '0' COMMENT '隔离邮件保存天数',
  `is_send_isolate` tinyint(1) NOT NULL DEFAULT '0' COMMENT '发送隔离报告',
  `send_isolate_name` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '隔离报告发件人',
  `isolate_url` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '隔离报告链接地址',
  `check_object` longtext CHARACTER SET utf8 COMMENT '检测对象',
  `check_local` longtext CHARACTER SET utf8 COMMENT '本域进站邮件',
  `check_outside` longtext CHARACTER SET utf8 COMMENT '外域进站邮件',
  `is_info` tinyint(1) NOT NULL DEFAULT '1' COMMENT '个人资料功能',
  `is_passwd_mdf` tinyint(1) NOT NULL DEFAULT '1' COMMENT '密码修改功能',
  `is_param` tinyint(1) NOT NULL DEFAULT '1' COMMENT '参数设置功能',
  `is_signature` tinyint(1) NOT NULL DEFAULT '1' COMMENT '邮件签名功能',
  `is_autoreply` tinyint(1) NOT NULL DEFAULT '1' COMMENT '自动回复功能',
  `is_autotans` tinyint(1) NOT NULL DEFAULT '1' COMMENT '自动转发功能',
  `is_blackwhite` tinyint(1) NOT NULL DEFAULT '1' COMMENT '黑白名单功能',
  `is_tansdefault` tinyint(1) NOT NULL DEFAULT '1' COMMENT '设置自动转发默认值',
  `is_move` tinyint(1) NOT NULL DEFAULT '1' COMMENT '邮箱搬家功能',
  `is_suggest` tinyint(1) NOT NULL DEFAULT '1' COMMENT '邮箱意见反馈功能',
  `is_view` tinyint(1) NOT NULL DEFAULT '1' COMMENT '邮件召回记录查看',
  `is_filter` tinyint(1) NOT NULL DEFAULT '1' COMMENT '邮件过滤功能',
  `is_smtp_tans` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'SMTP外发邮件中转',
  `passwd_level` tinyint(1) NOT NULL DEFAULT '1' COMMENT '账号密级',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
ALTER TABLE `core_group` ADD UNIQUE( `domain_id`, `name`);


CREATE TABLE `core_group_member` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL DEFAULT '0' COMMENT '组权限ID',
  `address` varchar(200) DEFAULT NULL COMMENT '邮箱',
  `name` varchar(80) DEFAULT NULL COMMENT '姓名',
  `remark` text COMMENT '备注',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
ALTER TABLE `core_group_member` ADD UNIQUE( `group_id`, `address`);

