# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maillist_id', models.IntegerField(default=0, verbose_name='\u5206\u7c7bID')),
                ('filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('filepath', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4fdd\u5b58\u8def\u5f84')),
                ('time_upload', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('time_import', models.DateTimeField(blank=True, null=True, verbose_name='\u5bfc\u5165\u65f6\u95f4')),
                ('time_finish', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('count_all', models.IntegerField(default=0, verbose_name='\u5730\u5740\u603b\u91cf')),
                ('count_err_1', models.IntegerField(default=0, verbose_name='\u65e0\u6548\u5730\u5740')),
                ('count_err_2', models.IntegerField(default=0, verbose_name='\u91cd\u590d\u5730\u5740')),
                ('status', models.CharField(choices=[('-1', '\u7b49\u5f85\u5bfc\u5165'), ('0', '\u6b63\u5728\u5bfc\u5165'), ('1', '\u5bfc\u5165\u6210\u529f'), ('-2', '\u5bfc\u5165\u5931\u8d25')], default='-1', max_length=1, verbose_name='\u72b6\u6001')),
                ('is_disorder', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6253\u4e71\u5bfc\u5165')),
            ],
            options={
                'db_table': 'ml_import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplaintList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='\u6295\u8bc9\u5730\u5740')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'ml_complaintlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.AutoField(db_column='list_id', primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=35, null=True, verbose_name='\u8054\u7cfb\u4eba\u5206\u7c7b\u540d\u79f0')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u8bf4\u660e\u4fe1\u606f')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'ml_maillist',
                'managed': False,
            },
        ),
    ]
