# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefTemplate',
            fields=[
                ('id', models.AutoField(db_column='template_id', primary_key=True, serialize=False)),
                ('manager_id', models.IntegerField(default=0)),
                ('agent_id', models.IntegerField(default=0)),
                ('customer_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6a21\u677f\u540d\u79f0')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4e3b\u9898')),
                ('content', models.TextField(blank=True, null=True, verbose_name='HTML\u5185\u5bb9')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528')], default=0, verbose_name='\u72b6\u6001')),
                ('thumb_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8def\u5f84')),
            ],
            options={
                'db_table': 'ms_ref_tpl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefTemplateCategory',
            fields=[
                ('id', models.AutoField(db_column='cate_id', primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
            ],
            options={
                'db_table': 'ms_ref_tpl_cate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SendAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('filetype', models.CharField(blank=True, max_length=35, null=True, verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('filepath', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6587\u4ef6\u8def\u5f84')),
                ('attachtype', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u9644\u4ef6\u8bbe\u7f6e')),
                ('size', models.IntegerField(default=0, verbose_name='\u9644\u4ef6\u5927\u5c0f')),
            ],
            options={
                'db_table': 'ms_send_attachment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SendSubject',
            fields=[
                ('id', models.AutoField(db_column='subject_id', primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u4ef6\u4e3b\u9898')),
            ],
            options={
                'db_table': 'ms_send_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SendTemplate',
            fields=[
                ('id', models.AutoField(db_column='template_id', primary_key=True, serialize=False)),
                ('content_type', models.SmallIntegerField(choices=[(1, '\u7f16\u8f91HTML\u6a21\u677f'), (2, '\u4e0a\u4f20EML\u90ae\u4ef6\u6587\u4ef6')], default=1, verbose_name='\u6a21\u677f\u7c7b\u578b')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6a21\u677f\u540d\u79f0')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u4ef6\u4e3b\u9898')),
                ('content', models.TextField(blank=True, null=True, verbose_name='HTML\u5185\u5bb9')),
                ('text_content', models.TextField(blank=True, help_text='\u6587\u672c\u5f62\u5f0f\u7684\u90ae\u4ef6\u5185\u5bb9', null=True, verbose_name='\u6587\u672c\u5185\u5bb9')),
                ('encoding', models.CharField(choices=[(b'base64', 'base64'), (b'quoted-printable', 'quoted-printable')], default='base64', max_length=50, verbose_name='\u90ae\u4ef6\u7f16\u7801')),
                ('character', models.CharField(choices=[(b'utf-8', 'utf-8'), (b'iso-8859-1', 'iso-8859-1'), (b'gb180308', 'gb180308'), (b'euc-jp', 'euc-jp')], default='utf-8', max_length=32, verbose_name='\u8f6c\u6362\u5b57\u7b26\u96c6')),
                ('image_encode', models.CharField(choices=[(b'N', '\u5426'), (b'Y', '\u662f')], default='N', help_text='\u5426\uff1a\u90ae\u4ef6\u5185\u7684\u56fe\u7247\u4f1a\u81ea\u52a8\u4e0a\u4f20\u5230U-Mail\u670d\u52a1\u5668\u4e0a\uff0c\u4ee5\u5916\u90e8\u56fe\u50cf\u94fe\u63a5\u7684\u65b9\u5f0f\u663e\u793a\u56fe\u7247\u3002\u662f\uff1a\u90ae\u4ef6\u6240\u4f7f\u7528\u7684\u56fe\u50cf\u5185\u5d4c\u5728\u90ae\u4ef6\u6d88\u606f\u4e2d\u3002 \u8fd9\u5c06\u5bfc\u81f4\u90ae\u4ef6\u5927\u5c0f\u7684\u589e\u52a0(\u6263\u9664\u66f4\u591a\u7fa4\u53d1\u70b9\u6570), \u4f46\u662f\u90ae\u4ef6\u5374\u53ef\u4ee5\u8131\u673a\u6d4f\u89c8\u3002 ', max_length=32, verbose_name='\u662f\u5426\u5185\u5d4c\u7167\u7247')),
                ('attachtype', models.CharField(choices=[(b'common', '\u4f20\u7edf\u5185\u5d4c\u9644\u4ef6'), (b'html', '\u5728\u7ebf\u9644\u4ef6')], default='common', help_text='\u4f20\u7edf\u9644\u4ef6\uff1a\u4ee5\u666e\u901a\u7684\u90ae\u4ef6\u9644\u4ef6\u5f62\u5f0f\u53d1\u9001\uff0c\u9644\u4ef6\u5927\u5c0f\u4f1a\u589e\u52a0\u90ae\u4ef6\u5927\u5c0f\uff0c\u4f46\u662f\u9644\u4ef6\u53ef\u4ee5\u8131\u673a\u67e5\u770b\u3002\u5728\u7ebf\u9644\u4ef6\uff1a\u90ae\u4ef6\u7684\u9644\u4ef6\u4ee5HTML\u8d85\u94fe\u63a5\u7684\u5f62\u5f0f\u5185\u5d4c\u5728\u90ae\u4ef6\u6d88\u606f\u4e2d\uff0c\u4e0d\u4f1a\u589e\u5927\u90ae\u4ef6\u5927\u5c0f\uff0c\u4f46\u662f\u9700\u8981\u7f51\u7edc\u624d\u53ef\u8bbf\u95ee\u3002 ', max_length=32, verbose_name='\u9644\u4ef6\u8bbe\u7f6e')),
                ('priority', models.CharField(choices=[(b'low', '\u666e\u901a'), (b'middle', '\u8f83\u9ad8'), (b'high', '\u6700\u9ad8')], default='low', help_text='\u6700\u9ad8\u6295\u9012\u7ea7\u522b\u5c062\u500d\u6263\u9664\u70b9\u6570\u3001\u8f83\u9ad8\u6295\u9012\u7ea7\u522b\u5c061.5\u500d\u6263\u9664\u70b9\u6570\u3002', max_length=32, verbose_name='\u4f18\u5148\u6295\u9012\u7ea7\u522b')),
                ('report', models.TextField(blank=True, null=True, verbose_name='\u62a5\u544a')),
                ('result', models.CharField(blank=True, choices=[(b'green', '\u5b89\u5168'), (b'red', '\u5371\u9669'), (b'yellow', '\u8b66\u544a')], max_length=16, null=True, verbose_name='\u68c0\u6d4b\u7ed3\u679c')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('status', models.CharField(choices=[(b'0', '\u542f\u7528'), (b'1', '\u7981\u7528')], default='0', max_length=1, verbose_name='\u72b6\u6001')),
                ('size', models.IntegerField(default=0, verbose_name='\u6587\u672c\u5927\u5c0f')),
                ('isvalid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'db_table': 'ms_send_template',
                'managed': False,
            },
        ),
    ]
