# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_weixin.models.wechat_menu


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpid', models.CharField(default=b'wx78d3f61147d5747c', max_length=200)),
                ('corpsecret', models.CharField(default=b'cce7e4f11fc518f7fff230079ab0edc9', max_length=200)),
                ('token', models.CharField(default=b'1rYhzQBmo8LFD6rsvFg0Konuf6ZnH5', max_length=1000)),
                ('aeskey', models.CharField(default=b'I0y40ySUF1shYPIUGMvvDKJFSKNqJAVZKwoA91Apcyg', max_length=1000)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('accesstoken', models.CharField(default=b'', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BasicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_name', models.CharField(default=b'', max_length=500)),
                ('from_user_name', models.CharField(default=b'', max_length=500)),
                ('create_time', models.CharField(default=b'', max_length=500)),
                ('message_type', models.CharField(default=b'', max_length=500)),
                ('event', models.CharField(default=b'', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BasicMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_name', models.CharField(default=b'', max_length=500)),
                ('from_user_name', models.CharField(default=b'', max_length=500)),
                ('create_time', models.CharField(default=b'', max_length=500)),
                ('message_type', models.CharField(default=b'', max_length=500)),
                ('message_id', models.CharField(default=b'', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MessageAutoReplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=b'', max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopLevelMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=b'click', max_length=10)),
                ('name', models.CharField(default=b'test', max_length=50)),
                ('key', models.CharField(default=django_weixin.models.wechat_menu.convert_uuid_to_string, max_length=100)),
                ('url', models.CharField(default=b'', max_length=1000)),
                ('sub_menu', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeChatServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip_list', models.CharField(blank=True, default=b'', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='KeFuMessage',
            fields=[
                ('basicmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicMessage')),
                ('message_content', models.TextField(default=b'')),
            ],
            bases=('django_weixin.basicmessage',),
        ),
        migrations.CreateModel(
            name='LinkMessage',
            fields=[
                ('basicmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicMessage')),
                ('title', models.CharField(default=b'', max_length=1000)),
                ('description', models.CharField(default=b'', max_length=1000)),
                ('url', models.CharField(default=b'', max_length=1000)),
            ],
            bases=('django_weixin.basicmessage',),
        ),
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('basicevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicEvent')),
                ('latitude', models.CharField(default=b'', max_length=500)),
                ('longitude', models.CharField(default=b'', max_length=500)),
                ('precision', models.CharField(default=b'', max_length=500)),
            ],
            bases=('django_weixin.basicevent',),
        ),
        migrations.CreateModel(
            name='LocationMessage',
            fields=[
                ('basicmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicMessage')),
                ('location_x', models.CharField(default=b'', max_length=1000)),
                ('location_y', models.CharField(default=b'', max_length=1000)),
                ('scale', models.CharField(default=b'', max_length=500)),
                ('label', models.CharField(default=b'', max_length=1000)),
            ],
            bases=('django_weixin.basicmessage',),
        ),
        migrations.CreateModel(
            name='MenuEvent',
            fields=[
                ('basicevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicEvent')),
                ('event_key', models.CharField(default=b'', max_length=500)),
            ],
            bases=('django_weixin.basicevent',),
        ),
        migrations.CreateModel(
            name='PicMessage',
            fields=[
                ('basicmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicMessage')),
                ('pic_url', models.CharField(default=b'', max_length=1000)),
                ('media_id', models.CharField(default=b'', max_length=1000)),
            ],
            bases=('django_weixin.basicmessage',),
        ),
        migrations.CreateModel(
            name='ScanQRcodeEvent',
            fields=[
                ('basicevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicEvent')),
                ('event_key', models.CharField(default=b'', max_length=500)),
                ('ticket', models.CharField(default=b'', max_length=500)),
            ],
            bases=('django_weixin.basicevent',),
        ),
        migrations.CreateModel(
            name='SmallVideoMessage',
            fields=[
                ('basicmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicMessage')),
                ('media_id', models.CharField(default=b'', max_length=1000)),
                ('thumb_media_id', models.CharField(default=b'', max_length=1000)),
            ],
            bases=('django_weixin.basicmessage',),
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('basicmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicMessage')),
                ('message_content', models.TextField(default=b'')),
            ],
            bases=('django_weixin.basicmessage',),
        ),
        migrations.CreateModel(
            name='VideoMessage',
            fields=[
                ('basicmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicMessage')),
                ('media_id', models.CharField(default=b'', max_length=1000)),
                ('thumb_media_id', models.CharField(default=b'', max_length=1000)),
            ],
            bases=('django_weixin.basicmessage',),
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('basicmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_weixin.BasicMessage')),
                ('media_id', models.CharField(default=b'', max_length=1000)),
                ('format', models.CharField(default=b'', max_length=20)),
            ],
            bases=('django_weixin.basicmessage',),
        ),
    ]
